### PR TITLE
Throw Error if Swig or Python is not found

### PR DESCRIPTION
**Pull request by Reflyer823**
Hi, I was having the same issue as #241 when using the `wifi_phy_hier.grc` flow graph. After I solved this issue, I found that when the system lacks the swig library, cmake does not prompt an error, but skips the compilation of the module, which confuses me at first. 
However, this issue has been fixed in the `maint-3.7` branch, but still exists in the `maint-3.8` branch. So I create a pull request for it. I hope this will make the project more user-friendly for first-time users.
Thanks!

### CODE REVIEW

**Comment by bastibl** [comment]
I'd say that this is an intended. Why do you want to force the user to compile the Python bindings? Maybe someone just wants to use the C++ library.

**Comment by Reflyer823** [comment]
> I'd say that this is an intended. Why do you want to force the user to compile the Python bindings? Maybe someone just wants to use the C++ library.

I throw this error in the `swig` sub `CMakeLists.txt`, not in the root `CMakeLists.txt`. If someone just wants to use the C++ library, he should comment the `add_subdirectory(swig)` line in the root `CMakeLists.txt`. 

Otherwise, my commit is the same as your commit b16ac24 on 9 Mar 2016. So I think it is also necessary in this branch.

**Comment by bastibl** [comment]
I made this change, because I was annoyed by people who didn't install Swig and wondered why there were no swig/python bindings. Yet, it's not the way things should be. It's not good practice to force users to comment out or in various directories based on the build they are trying to produce. Just think of GNU Radio with all its dependencies. You cannot tell people to change the build systems at various places. Also the official GNU Radio modtool does it like that: https://github.com/gnuradio/gnuradio/blob/maint-3.8/gr-utils/python/modtool/templates/gr-newmod/swig/CMakeLists.txt#L32-L38
It makes a lot of sense to stay as close as possible to this template. Otherwise every OOT reinvents the wheel and every OOT maintainer reinvents it differently. So I would suggest to keep it as is.

**Comment by Reflyer823** [comment]
> I made this change, because I was annoyed by people who didn't install Swig and wondered why there were no swig/python bindings. Yet, it's not the way things should be. It's not good practice to force users to comment out or in various directories based on the build they are trying to produce. Just think of GNU Radio with all its dependencies. You cannot tell people to change the build systems at various places. Also the official GNU Radio modtool does it like that: https://github.com/gnuradio/gnuradio/blob/maint-3.8/gr-utils/python/modtool/templates/gr-newmod/swig/CMakeLists.txt#L32-L38 It makes a lot of sense to stay as close as possible to this template. Otherwise every OOT reinvents the wheel and every OOT maintainer reinvents it differently. So I would suggest to keep it as is.

Thank you for replying me. I agree with your opinion. And I will close this PR after this reply.

**Pull request closed without merging**
