### PR TITLE
expose CSI-values and message received.

### PR DESCRIPTION
**Pull request by TheL1ne**
As it was asked multiple times and I needed it again I introduced a frameequalizer_block which exposes the CSI-values (without breaking existing workflows) and additionally I also exposed the message from the decode_mac as I need it in my code (maybe not as useful for others)

### CODE REVIEW

**Comment by TheL1ne** [comment]
additionally I found an issue that can cause a bug in your examples in my opinion @bastibl as the `phy-hier-block` was always estimating based on the same frequency.

**Comment by bastibl** [comment]
Thanks for the pull request. It looks very good! And you're right, considering the issues and questions regarding CSI, this is something that people are definitely interested in.
Atm, I have a hard time testing the patch since I cannot even install 3.7 on my current distribution. (Ubuntu 20.04 does not ship qwt for qt4). Out of curiosity, why are you still using 3.7? I'm wondering whether this should really be added to 3.7 or just ported to 3.8. What do you think?
One thing, one might want to add is the item tag at the beginning of the frame. Maybe it should also be added to the CSI output. It would also be great if the CSI related PRs could be squashed (atm there are commits that add it and follow-up commit that duplicate the block. That's a bit confusing to review.)
Regarding the frequency, this is really something that might confuse people and should be set. But it has no impact, since the frequency and sample rate parameters of the PHY are not used for the tx chain. (I just just changed that for master and maint-3.8, since there was also another thing I wanted to change.)

**Comment by TheL1ne** [comment]
I tried to inform myself before starting my bachelor thesis and read that 3.8 ist switching to python3  and that the implementation seems to be wonky. Therefore I used the latest "stable" version with 3.7. I hope the changes are transferable to 3.8.

Unfortunately I don't know which kind of `item tag` you want to add to the stream.

I thought you will just review the result and not single changes. Sorry that I did it a bit messy first and cleaned up afterwards. You should be able to `squash and merge` the PR in its entirety so that it will only show up as 1 commit in your project history.

**Comment by TheL1ne** [comment]
I tired to investigated a bit further and it seems I did mess something up with the swig builds. Sorry.

**Comment by bastibl** [comment]
You forgot to actually compile the block. It has to be added here:
https://github.com/bastibl/gr-ieee802-11/blob/maint-3.7/lib/CMakeLists.txt#L106
The header should also be added here:
https://github.com/bastibl/gr-ieee802-11/blob/maint-3.7/include/ieee802-11/CMakeLists.txt#L76

GNU Radio supports optional outputs, which may be the better approach than duplicating code. What would you think about having CSI as optional output of the equalizer?

**Comment by TheL1ne** [comment]
I tried using an optional port but unfortunately did not know how to detect from inside a block if this port is connected and the runtime crashed the moment I did sent something onto the optional unconnected port.
I will try to add you fixes mentioned above.

**Comment by TheL1ne** [comment]
@bastibl I have another question for background information: the values that I expose here in which kind of unit are they measured? in `dBm`?

**Comment by bastibl** [comment]
What you expose, seems to be the (unit-less) complex channel coefficient, i.e., the `h` in `sent_constellation_point = h * transmitted_constellation_point`.

**Comment by nlhnt** [comment]
Has this been merged? I am also interested in this functionality.

**Comment by bastibl** [comment]
I'm not sure about the current state of the PR. Would be great if you would just manually merge it, give it a try, and let us know if it worked for you.

**Comment by TheL1ne** [comment]
it has not been merged as I realised that I actually wanted other values and it was for an older version of the software so it was not easily mergable into the master branch.

**Comment by nlhnt** [comment]
I see, I will try to give it a try manually. I am quite new to GNU Radio so it will take some time probably.
What other values were you looking for?
I am interested in inverting the channel vector to do "precoding" which tries to compensate channel effects.
This usually takes place in GSM networks, but we got a different use case for that in 802.11.

**Comment by YunxiangCai** [comment]
> As it was asked multiple times and I needed it again I introduced a frameequalizer_block which exposes the CSI-values (without breaking existing workflows) and additionally I also exposed the message from the decode_mac as I need it in my code (maybe not as useful for others)

I have tried to expose the CSI values with your code, but the CSI phase signal I got is not stable (with a statstic environment). Have you got a stable CSI by this way?

**Comment by bastibl** [comment]
Could you please be a bit more specific about what you did and what exactly you consider "not stable".

**Comment by YunxiangCai** [comment]
> Could you please be a bit more specific about what you did and what exactly you consider "not stable".

In my opinion, the CSI represents the influence of environment on signal. The CSI should be stable with an unchanged environment. But when I expose the CSI and add a 'complex to arg' moudle to show the phase of CSI value, I found that the phase dramaticaly changed over time. I can't upload video here so I post two pictures. The fisrt window in to pictures show the CSI phase.


Screen Shot 2021-02-25 at 2 41 41 PM
Screen Shot 2021-02-25 at 2 41 51 PM

**Comment by bastibl** [comment]
It's not on the screenshot, so make sure that you display always a multiple of the data subcarriers, such that the first point always corresponds to the first data subcarrier. Otherwise it will look random.
Also the phase of the CSI will only be relatively static within one frame. The phase between frames is random, i.e., this is not the setup to check that the CSI is relatively constant. You could dump them to a file and see if there are successive symbols with similar CSI.

**Comment by bastibl** [comment]
A slightly different version was just merged:
https://github.com/bastibl/gr-ieee802-11/pull/294

I'll close this for now. Thank you!

**Pull request closed without merging**
