### PR TITLE
Fix spdlog compile issue

### PR DESCRIPTION
**Pull request by bkerler**
Fixes compilation due to https://github.com/gnuradio/gnuradio/issues/6278 on ubuntu 23.04 and gnuradio 3.11.

### CODE REVIEW

**Comment by bastibl** [comment]
I'm not sure I understand the problem. Isn't that something that GNU Radio should fix?

Or do you mean that all logging should be converted to a new format. In that case, logging messages have to change, no? Because this looks like it might create overhead.

**Comment by bkerler** [comment]
Hi, yes, the logging interface in gnuradio has a new format. In the past, the code using the GR_LOG* macros worked fine. But with new compilers this will now fail. This was a quick hack to compile your code, otherwise compilation will fail. However the right way would be that you need to convert all the GR_LOG_* messages to the new format. For example GR_LOG_DEBUG(d_logger,msg) would become d_logger->debug(msg) and format::boost messages are no longer supported (gnuradio removes support for boost). See https://wiki.gnuradio.org/index.php/Logging#Logging_in_C++

**Comment by bastibl** [comment]
I see, I converted it to a draft as a reminder to work on this. Either now or latest when we port to 3.11, once it is released.

**Comment by bastibl** [comment]
Wait, or are there also scenarios where this breaks for the 3.10 branch? Your comment refers to 3.11, but the linked issue suggests it could also breaks for 3.10? I guess breaking things in 3.10 should be something that has to be fixed upstream.

**Comment by bkerler** [comment]
Closing this issue, as it seems to be fixed in 3.10 now. But the problem is reintroduced in 3.11. Gonna upload a 3.11 PR instead. Issue now is updated spdlog, means should affect all gnuradio versions if a newer ubuntu version is used.

**Pull request closed without merging**
