### PR TITLE
Update to current master/pybind

### PR DESCRIPTION
**Pull request by mormj**
Adds pybind bindings for current master branch, and replaces boost::shared_ptr with std::shared_ptr

Signed-off-by: Josh Morman <jmorman@perspectalabs.com>

### CODE REVIEW

**Comment by bastibl** [comment]
Arg, obviously I didn't want to close this... I deleted the `master` branch, since I'm at the moment not actively tracking it. And it's probably confusing if the `master` of this module doesn't work with GNU Radio `master`.

I just pushed a `maint-3.9` branch that builds on your work.

I assume this a minimal port to GR 3.9 to make C++ (your benchmarks) work?
I tried to complete it, but atm I get segfaults, Python bindings are missing, the flowgraphs don't work, and I have a hard time testing without gr-foo. 

Anyway, there are some PyBind-related issues, you might know out of the top of your head: Do you know, why the Equalizer Enum in the Frame Equalizer get a Python binding, but the Encoding Enum from the Mapper doesn't?

Also this segfaults (which is why flowgraphs segfault during load in GRC):
```python
import ieee802_11
a = ieee802_11.signal_field()
b = a.formatter()
```

Creating this Python binding was a Pita with Swig. Do you know how to make it work with PyBind?

**Comment by mormj** [comment]
This was a minimal port to the pybind stuff so i didnt work though all the blocks/enums. Will look into that issue and build onto this PR

**Comment by bastibl** [comment]
Great, thanks! I'll also have another look. Would be great if you could build on the `maint-3.9` branch, which already includes this PR.

**Comment by bastibl** [comment]
The current maint-3.9 branch seems to work for me.

**Pull request closed without merging**
