### PR TITLE
Workaround occasional crashes using canary (temporary fix)

### PR DESCRIPTION
**Pull request by jonathanbrucker**
When running in a real-life 802.11a Wi-Fi environment with busy traffic,
the module occasionally crashes (segfault) and/or stops responding.
This was traced back to a out-of-bounds memory write in class
decode_mac_impl. I don't know the root cause.

As a temporary workaround, I moved around some class members that were
getting overwritten and added a canary to demonstrate the out-of-bounds
memory write. The module runs stable and doesn't crash after these
modifications.

Signed-off-by: Jonathan Brucker <jonathan.brucke@gmail.com>

### CODE REVIEW

**Comment by bastibl** [comment]
Thanks for the bug report. I it would be great if you could compile the module with debug information, run it in a debugger, and do a stack trace once it crashes.

**Comment by bastibl** [comment]
OK, don't worry. I can reproduce it. It happens when the frame is close to maximum size. I guess some buffer is not allocated large enough.

I will look into it.

**Comment by jonathanbrucker** [comment]
Stack trace is not very interesting, it shows that the class member named "copied" is overwritten (it should never have a negative value). Here it is:

    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7f25c37f6700 (LWP 23555)]
    0x00007f265e7dd765 in memcpy (__len=48, __src=0x7f262e271a00, __dest=0x237595f0)
        at /usr/include/x86_64-linux-gnu/bits/string3.h:51
    51    return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
    (gdb) bt
    #0  0x00007f265e7dd765 in memcpy (__len=48, __src=0x7f262e271a00, __dest=0x237595f0)
        at /usr/include/x86_64-linux-gnu/bits/string3.h:51
    #1  decode_mac_impl::general_work (this=0x374e3e0, noutput_items=<optimized out>,
        ninput_items=std::vector of length 1, capacity 1 = {...}, input_items=..., output_items=...)
        at /home/user/gnur/home/src/gr-ieee-80211/lib/decode_mac.cc:96

    (gdb) up

    (gdb) p copied
    $1 = -436207615

**Comment by bastibl** [comment]
Thanks, could you try adding a tag debug block after the frame equalizer to check if your crashes are also related to frames with a size of approx 1532 byte?

**Comment by jonathanbrucker** [comment]
It can take a long time for the module to crash, depending on what packets are in the air... Sadly I don't have the time right now to debug the issue (that's why I added the workaround). I'll try again when I have more time, or maybe implement fuzzing to speed up the debug process.

**Comment by bastibl** [comment]
I just pushed a commit that hopefully fixes it.

The problem if a full-sized frame with a high MCS was rounded up to the next complete OFDM symbol. This added a lot of encoded bytes, which were wrongly decoded in a buffer that was allocated according to the maximum payload size.

I close this for now. Please reopen and let me know if you still see segfaults.

**Pull request closed without merging**
