### PR TITLE
non-x86 support: Only use SSE2 when supported

### PR DESCRIPTION
**Pull request by swolfe0105**
Add generic version of viterbi decoder that does not utilize x86
intrinsics to provide support for other architectures such as ARM.

With this change I was able to compile and run this recipe on a Raspberry Pi 3

### CODE REVIEW

**Comment by bastibl** [comment]
Cool stuff! Did you test which RX bandwith you could reach with a Pi3?

Regarding the code, the many ifdefs are not really nice. It would be great if you could create two separate files for the two implementations and use only one ifdef for including the corresponding version.

**Comment by swolfe0105** [comment]
I don't have a good measurement measurement for RX bandwidth yet. I tested this on a build that doesn't have NEON enabled so it was very slow. I was receiving a couple MAC frames per second when sampling at 10MHz, but I think there would be a substantial performance increase if NEON was enabled.

About all the ifdefs, I should have mentioned that what I did was port changes over from gr-dtv, which seems to be where the gr-ieee-80211 viterbi decoder originated. I agree that it all these ifdefs isnt the cleanest approach, but I think it might be some advantageous to follow what gr-dtv is doing because it will be easier to port future changes back and forth (like I'm doing now).

gr-dtv's viterbi decoder: https://github.com/gnuradio/gnuradio/blob/master/gr-dtv/lib/dvbt/dvbt_viterbi_decoder_impl.cc

**Comment by swolfe0105** [comment]
Actually, I though some more and I think you're right, the ifdef approach isn't scalable if more architectural specific implementations are added. I'm considering writing a NEON implementation of the viterbi decoder for better performance on ARM, and it would be way too messy to continue down the ifdef road.

Creating separate files for each implementation is a better long term solution.  I plan on pushing more changes to do this.

**Comment by swolfe0105** [comment]
Okay, the latest commits restructure the viterbi decoder source to support multiple implementations. I did this in a manner similar to the way the equalizer is organized, but with some CMake and preprocessor logic to determine which implementation to build.

**Comment by bastibl** [comment]
This look very good. Thank you very much for working on that.

Unfortunately, I can't test it right now. My setup is totally broken, but it seems to be a known issue with Qt (https://github.com/gnuradio/gnuradio/issues/1059). I'll test the patch asap and will leave the pull request open until then. Hope that's OK for you.

**Comment by swolfe0105** [comment]
Thats fine with me :+1:

**Pull request merged**
